import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import GlobalLayout from "@/components/global-layout";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata = {
<<<<<<< HEAD
  title: "TodayEat",
=======
  title: "Create Next App",
>>>>>>> bbba67032a051d9dc382c3f3a33783bd61dd76ec
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="kr">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <GlobalLayout>{children}</GlobalLayout>
      </body>
    </html>
  );
}
